name = No Sidebar
description = No Sidebar
base theme = omega
template = no-sidebar-layout

engine = phptemplate
core = 7.x

; Stylesheets
stylesheets[all][] = css/sidebar.normalize.css
stylesheets[all][] = css/sidebar.hacks.css
stylesheets[all][] = css/sidebar.styles.css
stylesheets[all][] = css/didebar.no-query.css

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Styles
stylesheets[all][] = css/layouts/sidebar/no-sidebar.layout.css
stylesheets[all][] = css/layouts/sidebar/no-sidebar.layout.no-query.css